import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/app/components/assets/navbar/Navbar";
import {Children} from "react";
import ChildrenLayout from "@/app/components/assets/children/ChildrenLayout";
import {BackgroundBeamsWithCollision} from "@/app/components/assets/ui/BackgroundBeamsWithCollision";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Hub Link",
    description: "Generated by @realashrafi",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <BackgroundBeamsWithCollision>
            <Navbar/>
            <ChildrenLayout children={children}/>
        </BackgroundBeamsWithCollision>
        </body>
        </html>
    );
}
