import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/assets/navbar/Navbar";
import ChildrenLayout from "@/app/components/assets/children/ChildrenLayout";
// import {BackgroundBeamsWithCollision} from "@/app/components/assets/ui/BackgroundBeamsWithCollision";
import Providers from "@/app/components/assets/providers/providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Hub Link",
    description: "Generated by @realashrafi",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
        >
        <Providers>
            {/*<BackgroundBeamsWithCollision>*/}
                <Navbar/>
                <ChildrenLayout>
                    {children}
                </ChildrenLayout>
            {/*</BackgroundBeamsWithCollision>*/}
        </Providers>
        </body>
        </html>
    );
}
